cmake_minimum_required(VERSION 3.6 FATAL_ERROR)

set(TARGET_CPU "cortex-m3")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ${TARGET_CPU})

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

#set(CMAKE_C_COMPILER   "C:/Users/Pawel/AppData/Roaming/xPacks/ARM-NO~1/XPACK-~1.1/bin/AR653C~1.EXE")
#set(CMAKE_CXX_COMPILER "C:/Users/Pawel/AppData/Roaming/xPacks/ARM-NO~1/XPACK-~1.1/bin/AR10B2~1.EXE")
#set(CMAKE_ASM_COMPILER "C:/Users/Pawel/AppData/Roaming/xPacks/ARM-NO~1/XPACK-~1.1/bin/AR653C~1.EXE")
#set(CMAKE_SIZE_UTIL    "C:/Users/Pawel/AppData/Roaming/xPacks/ARM-NO~1/X\PACK-~1.1/bin/AR0A07~1.EXE")

set(CMAKE_C_COMPILER             "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR19DD~1.EXE")
set(CMAKE_CXX_COMPILER           "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR10B2~1.EXE")
set(CMAKE_ASM_COMPILER           "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR19DD~1.EXE")
set(CMAKE_SIZE_UTIL              "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR0A07~1.EXE")
set(CMAKE_OBJCOPY                "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/ARF839~1.EXE")
set(CMAKE_AR                     "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/ARM-NO~2.EXE")
set(CMAKE_OBJDUMP                "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR39F3~1.EXE")
set(CMAKE_ADDR2LINE              "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/ARM-NO~1.EXE")
set(CMAKE_ASM_COMPILER_AR        "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR743F~1.EXE")
set(CMAKE_ASM_COMPILER_RANLIB    "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR738D~1.EXE")
set(CMAKE_DLLTOOL                "C:/PROGRA~2/GNUTOO~1/92019-~1/bin/AR39F3~1.EXE")

set(COMMON_FLAGS "-mthumb -mcpu=${TARGET_CPU} -mno-thumb-interwork -mfpu=vfp -msoft-float -mfix-${TARGET_CPU}-ldrd")
set(C_CXX_FLAGS  "--specs=nano.specs -ffunction-sections -fdata-sections -ffreestanding")
set(CXX_FLAGS    "-fno-exceptions -fno-rtti -fno-threadsafe-statics")

set(CMAKE_C_FLAGS_INIT          "${COMMON_FLAGS} ${C_CXX_FLAGS} "              CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT        "${COMMON_FLAGS} ${C_CXX_FLAGS} ${CXX_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS_INIT        "${COMMON_FLAGS} -x assembler-with-cpp "       CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--gc-sections"                           CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS_DEBUG     "-Og -g"          CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG   "-Og -g"          CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE   "-Os -g -DNDEBUG" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE "-Os -g -DNDEBUG" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXPORT_COMPILE_COMMANDS             ON)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES    ON)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_LIBRARIES   ON)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS     ON)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES  ON)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_LIBRARIES ON)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS   ON)
set(CMAKE_NINJA_FORCE_RESPONSE_FILE           ON)

#added by Sapieron
SET (CMAKE_C_COMPILER_WORKS 1)
SET (CMAKE_CXX_COMPILER_WORKS 1)
